This is makeindex, version 2.15 [TeX Live 2018] (kpathsea + Thai support).
Scanning style file ./george_lancaster_thesis.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file george_lancaster_thesis.acn....done (341 entries accepted, 0 rejected).
Sorting entries......done (3330 comparisons).
Generating output file george_lancaster_thesis.acr....done (149 lines written, 0 warnings).
Output written in george_lancaster_thesis.acr.
Transcript written in george_lancaster_thesis.alg.
